package store

import (
	"fmt"
	"path/filepath"
	"strings"
	"time"

	"subtitle-ui/backend/internal/domain"
	"subtitle-ui/backend/internal/textsort"
)

const migrationV1 = `
CREATE TABLE IF NOT EXISTS videos (
  id TEXT PRIMARY KEY,
  path TEXT NOT NULL UNIQUE,
  directory TEXT NOT NULL,
  file_name TEXT NOT NULL,
  title TEXT NOT NULL,
  year TEXT NOT NULL DEFAULT '',
  metadata_source TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS subtitles (
  id TEXT PRIMARY KEY,
  video_id TEXT NOT NULL,
  path TEXT NOT NULL,
  file_name TEXT NOT NULL,
  language TEXT NOT NULL DEFAULT 'und',
  format TEXT NOT NULL DEFAULT '',
  size INTEGER NOT NULL DEFAULT 0,
  mod_time TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY(video_id) REFERENCES videos(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_subtitles_video_id ON subtitles(video_id);
CREATE INDEX IF NOT EXISTS idx_subtitles_path ON subtitles(path);

CREATE TABLE IF NOT EXISTS scan_runs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  started_at TEXT NOT NULL,
  finished_at TEXT NOT NULL,
  video_count INTEGER NOT NULL DEFAULT 0,
  error TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS operation_logs (
  id TEXT PRIMARY KEY,
  timestamp TEXT NOT NULL,
  action TEXT NOT NULL,
  video_id TEXT NOT NULL,
  target_path TEXT NOT NULL DEFAULT '',
  backup_path TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL,
  message TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_operation_logs_timestamp ON operation_logs(timestamp);
`

const migrationV1Postgres = `
CREATE TABLE IF NOT EXISTS videos (
  id TEXT PRIMARY KEY,
  path TEXT NOT NULL UNIQUE,
  directory TEXT NOT NULL,
  file_name TEXT NOT NULL,
  title TEXT NOT NULL,
  year TEXT NOT NULL DEFAULT '',
  metadata_source TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS subtitles (
  id TEXT PRIMARY KEY,
  video_id TEXT NOT NULL,
  path TEXT NOT NULL,
  file_name TEXT NOT NULL,
  language TEXT NOT NULL DEFAULT 'und',
  format TEXT NOT NULL DEFAULT '',
  size BIGINT NOT NULL DEFAULT 0,
  mod_time TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY(video_id) REFERENCES videos(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_subtitles_video_id ON subtitles(video_id);
CREATE INDEX IF NOT EXISTS idx_subtitles_path ON subtitles(path);

CREATE TABLE IF NOT EXISTS scan_runs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at TEXT NOT NULL,
  finished_at TEXT NOT NULL,
  video_count INTEGER NOT NULL DEFAULT 0,
  error TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS operation_logs (
  id TEXT PRIMARY KEY,
  timestamp TEXT NOT NULL,
  action TEXT NOT NULL,
  video_id TEXT NOT NULL,
  target_path TEXT NOT NULL DEFAULT '',
  backup_path TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL,
  message TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_operation_logs_timestamp ON operation_logs(timestamp);
`

const migrationV2 = `
ALTER TABLE videos ADD COLUMN media_type TEXT NOT NULL DEFAULT 'movie';
CREATE INDEX IF NOT EXISTS idx_videos_media_type ON videos(media_type);
`

const migrationV3 = `
ALTER TABLE videos ADD COLUMN poster_path TEXT NOT NULL DEFAULT '';
`

const migrationV4 = `
CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
`

const migrationV5AddSource = `
ALTER TABLE subtitles ADD COLUMN source TEXT NOT NULL DEFAULT 'directory';
`

const migrationV5AddSourceDetail = `
ALTER TABLE subtitles ADD COLUMN source_detail TEXT NOT NULL DEFAULT '';
`

var migrationV6VideoMetadataColumns = []struct {
	name      string
	statement string
}{
	{name: "original_title", statement: `ALTER TABLE videos ADD COLUMN original_title TEXT NOT NULL DEFAULT '';`},
	{name: "imdb_id", statement: `ALTER TABLE videos ADD COLUMN imdb_id TEXT NOT NULL DEFAULT '';`},
	{name: "tmdb_id", statement: `ALTER TABLE videos ADD COLUMN tmdb_id TEXT NOT NULL DEFAULT '';`},
	{name: "series_title", statement: `ALTER TABLE videos ADD COLUMN series_title TEXT NOT NULL DEFAULT '';`},
	{name: "series_original_title", statement: `ALTER TABLE videos ADD COLUMN series_original_title TEXT NOT NULL DEFAULT '';`},
	{name: "series_imdb_id", statement: `ALTER TABLE videos ADD COLUMN series_imdb_id TEXT NOT NULL DEFAULT '';`},
	{name: "series_tmdb_id", statement: `ALTER TABLE videos ADD COLUMN series_tmdb_id TEXT NOT NULL DEFAULT '';`},
}

func (s *Store) migrationV1SQL() string {
	if s.dialect == dialectPostgres {
		return migrationV1Postgres
	}
	return migrationV1
}

func (s *Store) backfillSubtitleSources() error {
	type backfillInfo struct {
		targetPath   string
		source       string
		sourceDetail string
	}

	rows, err := s.query(
		`SELECT target_path, action, message
FROM operation_logs
WHERE status = 'ok'
  AND action IN ('upload', 'replace', 'convert')
  AND trim(target_path) != ''
ORDER BY timestamp ASC`,
	)
	if err != nil {
		return err
	}
	defer rows.Close()

	latestByPath := make(map[string]backfillInfo, 32)
	for rows.Next() {
		var targetPath, action, message string
		if err := rows.Scan(&targetPath, &action, &message); err != nil {
			return err
		}
		info := backfillInfo{targetPath: targetPath}
		switch action {
		case "convert":
			info.source = domain.SubtitleSourceGenerated
			info.sourceDetail = strings.TrimSpace(strings.TrimPrefix(message, "generated from "))
		default:
			info.source = domain.SubtitleSourceUpload
			info.sourceDetail = filepath.Base(targetPath)
		}
		latestByPath[subtitlePathKey(targetPath)] = info
	}
	if err := rows.Err(); err != nil {
		return err
	}

	for _, info := range latestByPath {
		if info.sourceDetail == "" || info.sourceDetail == "." {
			info.sourceDetail = filepath.Base(info.targetPath)
		}
		if _, err := s.exec(
			`UPDATE subtitles SET source = ?, source_detail = ? WHERE lower(path) = lower(?)`,
			info.source,
			info.sourceDetail,
			info.targetPath,
		); err != nil {
			return err
		}
	}
	return nil
}
func (s *Store) migrate() error {
	if _, err := s.exec(`
CREATE TABLE IF NOT EXISTS schema_migrations (
  version INTEGER PRIMARY KEY,
  applied_at TEXT NOT NULL
)`); err != nil {
		return err
	}

	applied, err := s.isMigrationApplied(1)
	if err != nil {
		return err
	}
	if !applied {
		tx, err := s.db.Begin()
		if err != nil {
			return err
		}
		defer func() {
			if err != nil {
				_ = tx.Rollback()
			}
		}()

		if err = s.execScriptTx(tx, s.migrationV1SQL()); err != nil {
			return fmt.Errorf("apply migration v1: %w", err)
		}
		if _, err = s.execTx(tx, `INSERT INTO schema_migrations(version, applied_at) VALUES(?, ?)`, 1, time.Now().UTC().Format(time.RFC3339Nano)); err != nil {
			return err
		}
		if err = tx.Commit(); err != nil {
			return err
		}
	}

	applied, err = s.isMigrationApplied(2)
	if err != nil {
		return err
	}
	if !applied {
		hasMediaType, err := s.hasColumn("videos", "media_type")
		if err != nil {
			return err
		}
		if !hasMediaType {
			if err := s.execScript(migrationV2); err != nil {
				return fmt.Errorf("apply migration v2: %w", err)
			}
		}
		if _, err = s.exec(`INSERT INTO schema_migrations(version, applied_at) VALUES(?, ?)`, 2, time.Now().UTC().Format(time.RFC3339Nano)); err != nil {
			return err
		}
	}

	applied, err = s.isMigrationApplied(3)
	if err != nil {
		return err
	}
	if !applied {
		hasPosterPath, err := s.hasColumn("videos", "poster_path")
		if err != nil {
			return err
		}
		if !hasPosterPath {
			if _, err := s.exec(migrationV3); err != nil {
				return fmt.Errorf("apply migration v3: %w", err)
			}
		}
		if _, err := s.exec(`INSERT INTO schema_migrations(version, applied_at) VALUES(?, ?)`, 3, time.Now().UTC().Format(time.RFC3339Nano)); err != nil {
			return err
		}
	}

	applied, err = s.isMigrationApplied(4)
	if err != nil {
		return err
	}
	if !applied {
		if err := s.execScript(migrationV4); err != nil {
			return fmt.Errorf("apply migration v4: %w", err)
		}
		if _, err := s.exec(`INSERT INTO schema_migrations(version, applied_at) VALUES(?, ?)`, 4, time.Now().UTC().Format(time.RFC3339Nano)); err != nil {
			return err
		}
	}

	applied, err = s.isMigrationApplied(5)
	if err != nil {
		return err
	}
	if !applied {
		hasSource, err := s.hasColumn("subtitles", "source")
		if err != nil {
			return err
		}
		if !hasSource {
			if _, err := s.exec(migrationV5AddSource); err != nil {
				return fmt.Errorf("apply migration v5 source: %w", err)
			}
		}
		hasSourceDetail, err := s.hasColumn("subtitles", "source_detail")
		if err != nil {
			return err
		}
		if !hasSourceDetail {
			if _, err := s.exec(migrationV5AddSourceDetail); err != nil {
				return fmt.Errorf("apply migration v5 source_detail: %w", err)
			}
		}
		if err := s.backfillSubtitleSources(); err != nil {
			return fmt.Errorf("backfill migration v5 subtitle sources: %w", err)
		}
		if _, err := s.exec(`INSERT INTO schema_migrations(version, applied_at) VALUES(?, ?)`, 5, time.Now().UTC().Format(time.RFC3339Nano)); err != nil {
			return err
		}
	}

	applied, err = s.isMigrationApplied(6)
	if err != nil {
		return err
	}
	if !applied {
		for _, column := range migrationV6VideoMetadataColumns {
			hasMetadataColumn, err := s.hasColumn("videos", column.name)
			if err != nil {
				return err
			}
			if !hasMetadataColumn {
				if _, err := s.exec(column.statement); err != nil {
					return fmt.Errorf("apply migration v6 %s: %w", column.name, err)
				}
			}
		}
		if _, err := s.exec(`INSERT INTO schema_migrations(version, applied_at) VALUES(?, ?)`, 6, time.Now().UTC().Format(time.RFC3339Nano)); err != nil {
			return err
		}
	}

	applied, err = s.isMigrationApplied(7)
	if err != nil {
		return err
	}
	if !applied {
		hasTitleSortKey, err := s.hasColumn("videos", "title_sort_key")
		if err != nil {
			return err
		}
		if !hasTitleSortKey {
			if _, err := s.exec(`ALTER TABLE videos ADD COLUMN title_sort_key TEXT NOT NULL DEFAULT ''`); err != nil {
				return fmt.Errorf("apply migration v7 title_sort_key: %w", err)
			}
		}
		if err := s.backfillTitleSortKeys(); err != nil {
			return fmt.Errorf("backfill migration v7 title_sort_key: %w", err)
		}
		if _, err := s.exec(`CREATE INDEX IF NOT EXISTS idx_videos_title_sort_key ON videos(title_sort_key)`); err != nil {
			return fmt.Errorf("apply migration v7 index: %w", err)
		}
		if _, err := s.exec(`INSERT INTO schema_migrations(version, applied_at) VALUES(?, ?)`, 7, time.Now().UTC().Format(time.RFC3339Nano)); err != nil {
			return err
		}
	}

	applied, err = s.isMigrationApplied(8)
	if err != nil {
		return err
	}
	if !applied {
		for _, column := range []struct {
			name      string
			statement string
		}{
			{name: "file_size", statement: `ALTER TABLE videos ADD COLUMN file_size INTEGER NOT NULL DEFAULT 0`},
			{name: "file_mod_time", statement: `ALTER TABLE videos ADD COLUMN file_mod_time TEXT NOT NULL DEFAULT ''`},
			{name: "scan_fingerprint", statement: `ALTER TABLE videos ADD COLUMN scan_fingerprint TEXT NOT NULL DEFAULT ''`},
		} {
			hasColumn, err := s.hasColumn("videos", column.name)
			if err != nil {
				return err
			}
			if !hasColumn {
				if _, err := s.exec(column.statement); err != nil {
					return fmt.Errorf("apply migration v8 %s: %w", column.name, err)
				}
			}
		}
		if _, err := s.exec(`INSERT INTO schema_migrations(version, applied_at) VALUES(?, ?)`, 8, time.Now().UTC().Format(time.RFC3339Nano)); err != nil {
			return err
		}
	}

	if s.dialect == dialectPostgres {
		if _, err := s.exec(`
CREATE TABLE IF NOT EXISTS data_migrations (
  name TEXT PRIMARY KEY,
  source TEXT NOT NULL DEFAULT '',
  applied_at TEXT NOT NULL,
  details TEXT NOT NULL DEFAULT ''
)`); err != nil {
			return fmt.Errorf("create data migrations table: %w", err)
		}
	}

	return nil
}

func (s *Store) backfillTitleSortKeys() error {
	rows, err := s.query(`SELECT id, title FROM videos`)
	if err != nil {
		return err
	}
	defer rows.Close()

	type row struct {
		id    string
		title string
	}
	items := make([]row, 0, 128)
	for rows.Next() {
		var item row
		if err := rows.Scan(&item.id, &item.title); err != nil {
			return err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return err
	}

	for _, item := range items {
		if _, err := s.exec(`UPDATE videos SET title_sort_key = ? WHERE id = ?`, textsort.SortKey(item.title), item.id); err != nil {
			return err
		}
	}
	return nil
}

func (s *Store) isMigrationApplied(version int) (bool, error) {
	row := s.queryRow(`SELECT COUNT(1) FROM schema_migrations WHERE version = ?`, version)
	var count int
	if err := row.Scan(&count); err != nil {
		return false, err
	}
	return count > 0, nil
}

func (s *Store) hasColumn(tableName string, columnName string) (bool, error) {
	if s.dialect == dialectPostgres {
		row := s.queryRow(
			`SELECT COUNT(1)
FROM information_schema.columns
WHERE table_schema = current_schema()
  AND table_name = ?
  AND column_name = ?`,
			tableName,
			columnName,
		)
		var count int
		if err := row.Scan(&count); err != nil {
			return false, err
		}
		return count > 0, nil
	}

	rows, err := s.query(`PRAGMA table_info(` + tableName + `)`)
	if err != nil {
		return false, err
	}
	defer rows.Close()

	for rows.Next() {
		var (
			cid        int
			name       string
			colType    string
			notNull    int
			defaultV   any
			primaryKey int
		)
		if err := rows.Scan(&cid, &name, &colType, &notNull, &defaultV, &primaryKey); err != nil {
			return false, err
		}
		if strings.EqualFold(name, columnName) {
			return true, nil
		}
	}
	return false, rows.Err()
}
