package store

import (
	"database/sql"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	_ "github.com/jackc/pgx/v5/stdlib"
	_ "modernc.org/sqlite"

	"subtitle-ui/backend/internal/domain"
)

const migrationV1 = `
CREATE TABLE IF NOT EXISTS videos (
  id TEXT PRIMARY KEY,
  path TEXT NOT NULL UNIQUE,
  directory TEXT NOT NULL,
  file_name TEXT NOT NULL,
  title TEXT NOT NULL,
  year TEXT NOT NULL DEFAULT '',
  metadata_source TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS subtitles (
  id TEXT PRIMARY KEY,
  video_id TEXT NOT NULL,
  path TEXT NOT NULL,
  file_name TEXT NOT NULL,
  language TEXT NOT NULL DEFAULT 'und',
  format TEXT NOT NULL DEFAULT '',
  size INTEGER NOT NULL DEFAULT 0,
  mod_time TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY(video_id) REFERENCES videos(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_subtitles_video_id ON subtitles(video_id);
CREATE INDEX IF NOT EXISTS idx_subtitles_path ON subtitles(path);

CREATE TABLE IF NOT EXISTS scan_runs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  started_at TEXT NOT NULL,
  finished_at TEXT NOT NULL,
  video_count INTEGER NOT NULL DEFAULT 0,
  error TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS operation_logs (
  id TEXT PRIMARY KEY,
  timestamp TEXT NOT NULL,
  action TEXT NOT NULL,
  video_id TEXT NOT NULL,
  target_path TEXT NOT NULL DEFAULT '',
  backup_path TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL,
  message TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_operation_logs_timestamp ON operation_logs(timestamp);
`

const migrationV1Postgres = `
CREATE TABLE IF NOT EXISTS videos (
  id TEXT PRIMARY KEY,
  path TEXT NOT NULL UNIQUE,
  directory TEXT NOT NULL,
  file_name TEXT NOT NULL,
  title TEXT NOT NULL,
  year TEXT NOT NULL DEFAULT '',
  metadata_source TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS subtitles (
  id TEXT PRIMARY KEY,
  video_id TEXT NOT NULL,
  path TEXT NOT NULL,
  file_name TEXT NOT NULL,
  language TEXT NOT NULL DEFAULT 'und',
  format TEXT NOT NULL DEFAULT '',
  size BIGINT NOT NULL DEFAULT 0,
  mod_time TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY(video_id) REFERENCES videos(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_subtitles_video_id ON subtitles(video_id);
CREATE INDEX IF NOT EXISTS idx_subtitles_path ON subtitles(path);

CREATE TABLE IF NOT EXISTS scan_runs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at TEXT NOT NULL,
  finished_at TEXT NOT NULL,
  video_count INTEGER NOT NULL DEFAULT 0,
  error TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS operation_logs (
  id TEXT PRIMARY KEY,
  timestamp TEXT NOT NULL,
  action TEXT NOT NULL,
  video_id TEXT NOT NULL,
  target_path TEXT NOT NULL DEFAULT '',
  backup_path TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL,
  message TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_operation_logs_timestamp ON operation_logs(timestamp);
`

const migrationV2 = `
ALTER TABLE videos ADD COLUMN media_type TEXT NOT NULL DEFAULT 'movie';
CREATE INDEX IF NOT EXISTS idx_videos_media_type ON videos(media_type);
`

const migrationV3 = `
ALTER TABLE videos ADD COLUMN poster_path TEXT NOT NULL DEFAULT '';
`

const migrationV4 = `
CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
`

const migrationV5AddSource = `
ALTER TABLE subtitles ADD COLUMN source TEXT NOT NULL DEFAULT 'directory';
`

const migrationV5AddSourceDetail = `
ALTER TABLE subtitles ADD COLUMN source_detail TEXT NOT NULL DEFAULT '';
`

var migrationV6VideoMetadataColumns = []struct {
	name      string
	statement string
}{
	{name: "original_title", statement: `ALTER TABLE videos ADD COLUMN original_title TEXT NOT NULL DEFAULT '';`},
	{name: "imdb_id", statement: `ALTER TABLE videos ADD COLUMN imdb_id TEXT NOT NULL DEFAULT '';`},
	{name: "tmdb_id", statement: `ALTER TABLE videos ADD COLUMN tmdb_id TEXT NOT NULL DEFAULT '';`},
	{name: "series_title", statement: `ALTER TABLE videos ADD COLUMN series_title TEXT NOT NULL DEFAULT '';`},
	{name: "series_original_title", statement: `ALTER TABLE videos ADD COLUMN series_original_title TEXT NOT NULL DEFAULT '';`},
	{name: "series_imdb_id", statement: `ALTER TABLE videos ADD COLUMN series_imdb_id TEXT NOT NULL DEFAULT '';`},
	{name: "series_tmdb_id", statement: `ALTER TABLE videos ADD COLUMN series_tmdb_id TEXT NOT NULL DEFAULT '';`},
}

type Store struct {
	db      *sql.DB
	dialect sqlDialect
}

type subtitleSourceInfo struct {
	Source       string
	SourceDetail string
}

type Driver string

const (
	DriverSQLite   Driver = "sqlite"
	DriverPostgres Driver = "postgres"
)

type OpenOptions struct {
	Driver      Driver
	SQLitePath  string
	PostgresURL string
}

type sqlDialect string

const (
	dialectSQLite   sqlDialect = "sqlite"
	dialectPostgres sqlDialect = "postgres"
)

const sqliteInitialDataMigration = "sqlite_initial_import"

func Open(dbPath string) (*Store, error) {
	return OpenWithOptions(OpenOptions{
		Driver:     DriverSQLite,
		SQLitePath: dbPath,
	})
}

func OpenWithOptions(options OpenOptions) (*Store, error) {
	driver := options.Driver
	if driver == "" {
		if strings.TrimSpace(options.PostgresURL) != "" {
			driver = DriverPostgres
		} else {
			driver = DriverSQLite
		}
	}

	switch driver {
	case DriverPostgres:
		return openPostgres(options.PostgresURL, options.SQLitePath)
	case DriverSQLite:
		return openSQLite(options.SQLitePath)
	default:
		return nil, fmt.Errorf("unsupported database driver %q", driver)
	}
}

func openSQLite(dbPath string) (*Store, error) {
	absPath, err := filepath.Abs(dbPath)
	if err != nil {
		return nil, err
	}
	if err := os.MkdirAll(filepath.Dir(absPath), 0o755); err != nil {
		return nil, err
	}

	db, err := sql.Open("sqlite", absPath)
	if err != nil {
		return nil, err
	}
	db.SetMaxOpenConns(1)

	if _, err := db.Exec(`PRAGMA foreign_keys = ON;`); err != nil {
		_ = db.Close()
		return nil, err
	}

	s := &Store{db: db, dialect: dialectSQLite}
	if err := s.migrate(); err != nil {
		_ = db.Close()
		return nil, err
	}
	return s, nil
}

func openPostgres(databaseURL string, sqlitePath string) (*Store, error) {
	dsn := strings.TrimSpace(databaseURL)
	if dsn == "" {
		return nil, errors.New("postgres database URL is required")
	}

	db, err := sql.Open("pgx", dsn)
	if err != nil {
		return nil, err
	}
	db.SetMaxOpenConns(10)
	db.SetMaxIdleConns(5)
	db.SetConnMaxLifetime(time.Hour)

	if err := db.Ping(); err != nil {
		_ = db.Close()
		return nil, err
	}

	s := &Store{db: db, dialect: dialectPostgres}
	if err := s.migrate(); err != nil {
		_ = db.Close()
		return nil, err
	}
	if err := s.migrateInitialSQLiteData(sqlitePath); err != nil {
		_ = db.Close()
		return nil, err
	}
	return s, nil
}

func (s *Store) Close() error {
	if s == nil || s.db == nil {
		return nil
	}
	return s.db.Close()
}

func (s *Store) DatabaseType() string {
	if s == nil {
		return string(dialectSQLite)
	}
	if s.dialect == dialectPostgres {
		return string(dialectPostgres)
	}
	return string(dialectSQLite)
}

func (s *Store) exec(query string, args ...any) (sql.Result, error) {
	return s.db.Exec(s.rebind(query), args...)
}

func (s *Store) query(query string, args ...any) (*sql.Rows, error) {
	return s.db.Query(s.rebind(query), args...)
}

func (s *Store) queryRow(query string, args ...any) *sql.Row {
	return s.db.QueryRow(s.rebind(query), args...)
}

func (s *Store) execTx(tx *sql.Tx, query string, args ...any) (sql.Result, error) {
	return tx.Exec(s.rebind(query), args...)
}

func (s *Store) execScript(query string) error {
	for _, statement := range strings.Split(query, ";") {
		statement = strings.TrimSpace(statement)
		if statement == "" {
			continue
		}
		if _, err := s.exec(statement); err != nil {
			return err
		}
	}
	return nil
}

func (s *Store) execScriptTx(tx *sql.Tx, query string) error {
	for _, statement := range strings.Split(query, ";") {
		statement = strings.TrimSpace(statement)
		if statement == "" {
			continue
		}
		if _, err := s.execTx(tx, statement); err != nil {
			return err
		}
	}
	return nil
}

func (s *Store) queryTx(tx *sql.Tx, query string, args ...any) (*sql.Rows, error) {
	return tx.Query(s.rebind(query), args...)
}

func (s *Store) queryRowTx(tx *sql.Tx, query string, args ...any) *sql.Row {
	return tx.QueryRow(s.rebind(query), args...)
}

func (s *Store) rebind(query string) string {
	if s.dialect != dialectPostgres {
		return query
	}

	var b strings.Builder
	b.Grow(len(query) + 8)
	index := 1
	for _, r := range query {
		if r == '?' {
			b.WriteByte('$')
			b.WriteString(fmt.Sprint(index))
			index += 1
			continue
		}
		b.WriteRune(r)
	}
	return b.String()
}

func placeholders(count int) string {
	if count <= 0 {
		return ""
	}
	out := make([]string, count)
	for i := range out {
		out[i] = "?"
	}
	return strings.Join(out, ",")
}

func (s *Store) insertPrefix() string {
	if s.dialect == dialectSQLite {
		return "INSERT OR REPLACE"
	}
	return "INSERT"
}

func (s *Store) migrationV1SQL() string {
	if s.dialect == dialectPostgres {
		return migrationV1Postgres
	}
	return migrationV1
}

func (s *Store) SaveScanResult(videos []domain.Video, startedAt time.Time, finishedAt time.Time, scanErr string) error {
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			_ = tx.Rollback()
		}
	}()

	_, err = s.execTx(
		tx,
		`INSERT INTO scan_runs(started_at, finished_at, video_count, error) VALUES(?, ?, ?, ?)`,
		startedAt.UTC().Format(time.RFC3339Nano),
		finishedAt.UTC().Format(time.RFC3339Nano),
		len(videos),
		scanErr,
	)
	if err != nil {
		return err
	}

	if scanErr == "" || len(videos) > 0 {
		existingSubtitleSources, err := s.loadSubtitleSourcesTx(tx, "")
		if err != nil {
			return err
		}
		if _, err = s.execTx(tx, `DELETE FROM subtitles`); err != nil {
			return err
		}
		if _, err = s.execTx(tx, `DELETE FROM videos`); err != nil {
			return err
		}

		for _, video := range videos {
			_, err = s.execTx(
				tx,
				s.insertPrefix()+` INTO videos(id, path, directory, file_name, title, original_title, year, imdb_id, tmdb_id, media_type, metadata_source, series_title, series_original_title, series_imdb_id, series_tmdb_id, poster_path, updated_at)
VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
				video.ID,
				video.Path,
				video.Directory,
				video.FileName,
				video.Title,
				video.OriginalTitle,
				video.Year,
				video.ImdbID,
				video.TmdbID,
				defaultMediaType(video.MediaType),
				video.MetadataSource,
				video.SeriesTitle,
				video.SeriesOriginalTitle,
				video.SeriesImdbID,
				video.SeriesTmdbID,
				video.PosterPath,
				video.UpdatedAt.UTC().Format(time.RFC3339Nano),
			)
			if err != nil {
				return err
			}

			for _, sub := range video.Subtitles {
				sub = mergeSubtitleSource(sub, existingSubtitleSources)
				_, err = s.execTx(
					tx,
					s.insertPrefix()+` INTO subtitles(id, video_id, path, file_name, language, format, size, mod_time, updated_at, source, source_detail)
VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
					sub.ID,
					video.ID,
					sub.Path,
					sub.FileName,
					sub.Language,
					sub.Format,
					sub.Size,
					sub.ModTime.UTC().Format(time.RFC3339Nano),
					video.UpdatedAt.UTC().Format(time.RFC3339Nano),
					sub.Source,
					sub.SourceDetail,
				)
				if err != nil {
					return err
				}
			}
		}
	}

	return tx.Commit()
}

func (s *Store) ListVideos(query string, mediaType string, directory string, page int, pageSize int, sortBy string, sortOrder string) ([]domain.Video, int, error) {
	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 30
	}
	if pageSize > 200 {
		pageSize = 200
	}

	baseQuery := `SELECT id, path, directory, file_name, title, original_title, year, imdb_id, tmdb_id, media_type, metadata_source, series_title, series_original_title, series_imdb_id, series_tmdb_id, poster_path, updated_at FROM videos`
	args := []any{}
	conditions := make([]string, 0, 2)

	needle := strings.TrimSpace(strings.ToLower(query))
	if needle != "" {
		conditions = append(conditions, `(lower(title) LIKE ? OR lower(original_title) LIKE ? OR lower(series_title) LIKE ? OR lower(series_original_title) LIKE ? OR lower(path) LIKE ?)`)
		like := "%" + needle + "%"
		args = append(args, like, like, like, like, like)
	}
	typeFilter := normalizeMediaType(mediaType)
	if typeFilter != "" {
		conditions = append(conditions, `media_type = ?`)
		args = append(args, typeFilter)
	}
	dirFilter := strings.TrimSpace(directory)
	if dirFilter != "" {
		normalized := strings.ToLower(strings.ReplaceAll(strings.TrimRight(dirFilter, "/\\"), "\\", "/"))
		conditions = append(conditions, `(lower(path) LIKE ? OR lower(replace(path, '\', '/')) LIKE ?)`)
		args = append(args, strings.ToLower(strings.TrimRight(dirFilter, "/\\"))+"%", normalized+"%")
	}
	if len(conditions) > 0 {
		baseQuery += ` WHERE ` + strings.Join(conditions, " AND ")
	}

	countQuery := `SELECT COUNT(1) FROM videos`
	if len(conditions) > 0 {
		countQuery += ` WHERE ` + strings.Join(conditions, " AND ")
	}
	total, err := s.countByQuery(countQuery, args)
	if err != nil {
		return nil, 0, err
	}

	offset := (page - 1) * pageSize
	baseQuery += " " + s.buildVideoOrderBy(sortBy, sortOrder) + ` LIMIT ? OFFSET ?`
	args = append(args, pageSize, offset)

	rows, err := s.query(baseQuery, args...)
	if err != nil {
		return nil, 0, err
	}
	defer rows.Close()

	out := make([]domain.Video, 0, 64)
	for rows.Next() {
		video, err := scanVideoRow(rows)
		if err != nil {
			return nil, 0, err
		}
		out = append(out, video)
	}
	if err := rows.Err(); err != nil {
		return nil, 0, err
	}

	// Batch-load subtitles after the main rows cursor is closed to avoid
	// single-connection SQLite deadlocks.
	if err := s.attachSubtitles(out); err != nil {
		return nil, 0, err
	}

	return out, total, nil
}

func (s *Store) GetVideo(videoID string) (domain.Video, bool, error) {
	row := s.queryRow(
		`SELECT id, path, directory, file_name, title, original_title, year, imdb_id, tmdb_id, media_type, metadata_source, series_title, series_original_title, series_imdb_id, series_tmdb_id, poster_path, updated_at FROM videos WHERE id = ?`,
		videoID,
	)

	var (
		video      domain.Video
		posterPath string
		updatedRaw string
	)
	err := row.Scan(
		&video.ID,
		&video.Path,
		&video.Directory,
		&video.FileName,
		&video.Title,
		&video.OriginalTitle,
		&video.Year,
		&video.ImdbID,
		&video.TmdbID,
		&video.MediaType,
		&video.MetadataSource,
		&video.SeriesTitle,
		&video.SeriesOriginalTitle,
		&video.SeriesImdbID,
		&video.SeriesTmdbID,
		&posterPath,
		&updatedRaw,
	)
	if errors.Is(err, sql.ErrNoRows) {
		return domain.Video{}, false, nil
	}
	if err != nil {
		return domain.Video{}, false, err
	}
	video.PosterPath = posterPath
	video.UpdatedAt = parseTimeOrNow(updatedRaw)

	subs, err := s.listSubtitlesByVideoID(video.ID)
	if err != nil {
		return domain.Video{}, false, err
	}
	video.Subtitles = subs
	return video, true, nil
}

func (s *Store) UpdateVideoSubtitles(videoID string, subtitles []domain.Subtitle, updatedAt time.Time) error {
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			_ = tx.Rollback()
		}
	}()

	res, err := s.execTx(tx, `UPDATE videos SET updated_at = ? WHERE id = ?`, updatedAt.UTC().Format(time.RFC3339Nano), videoID)
	if err != nil {
		return err
	}
	affected, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if affected == 0 {
		return sql.ErrNoRows
	}

	existingSubtitleSources, err := s.loadSubtitleSourcesTx(tx, videoID)
	if err != nil {
		return err
	}
	if _, err = s.execTx(tx, `DELETE FROM subtitles WHERE video_id = ?`, videoID); err != nil {
		return err
	}
	for _, sub := range subtitles {
		sub = mergeSubtitleSource(sub, existingSubtitleSources)
		_, err = s.execTx(
			tx,
			`INSERT INTO subtitles(id, video_id, path, file_name, language, format, size, mod_time, updated_at, source, source_detail)
VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
			sub.ID,
			videoID,
			sub.Path,
			sub.FileName,
			sub.Language,
			sub.Format,
			sub.Size,
			sub.ModTime.UTC().Format(time.RFC3339Nano),
			updatedAt.UTC().Format(time.RFC3339Nano),
			sub.Source,
			sub.SourceDetail,
		)
		if err != nil {
			return err
		}
	}
	return tx.Commit()
}

func (s *Store) AppendLog(log domain.OperationLog) error {
	_, err := s.exec(
		`INSERT INTO operation_logs(id, timestamp, action, video_id, target_path, backup_path, status, message)
VALUES(?, ?, ?, ?, ?, ?, ?, ?)`,
		log.ID,
		log.Timestamp.UTC().Format(time.RFC3339Nano),
		log.Action,
		log.VideoID,
		log.TargetPath,
		log.BackupPath,
		log.Status,
		log.Message,
	)
	return err
}

func (s *Store) ListLogs(page int, pageSize int) ([]domain.OperationLog, int, error) {
	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 8
	}
	if pageSize > 200 {
		pageSize = 200
	}

	total, err := s.countByQuery(`SELECT COUNT(1) FROM operation_logs`, nil)
	if err != nil {
		return nil, 0, err
	}

	offset := (page - 1) * pageSize
	rows, err := s.query(
		`SELECT id, timestamp, action, video_id, target_path, backup_path, status, message
FROM operation_logs ORDER BY timestamp DESC, id DESC LIMIT ? OFFSET ?`,
		pageSize,
		offset,
	)
	if err != nil {
		return nil, 0, err
	}
	defer rows.Close()

	out := make([]domain.OperationLog, 0, pageSize)
	for rows.Next() {
		var (
			log       domain.OperationLog
			timeValue string
		)
		if err := rows.Scan(
			&log.ID,
			&timeValue,
			&log.Action,
			&log.VideoID,
			&log.TargetPath,
			&log.BackupPath,
			&log.Status,
			&log.Message,
		); err != nil {
			return nil, 0, err
		}
		log.Timestamp = parseTimeOrNow(timeValue)
		out = append(out, log)
	}
	if err := rows.Err(); err != nil {
		return nil, 0, err
	}
	return out, total, nil
}

func (s *Store) ClearLogs() error {
	_, err := s.exec(`DELETE FROM operation_logs`)
	return err
}

func (s *Store) GetAppSettings(keys []string) (map[string]domain.AppSetting, error) {
	out := make(map[string]domain.AppSetting, len(keys))
	if len(keys) == 0 {
		return out, nil
	}

	placeholders := make([]string, len(keys))
	args := make([]any, len(keys))
	for i, key := range keys {
		placeholders[i] = "?"
		args[i] = key
	}

	rows, err := s.query(
		`SELECT key, value, updated_at FROM app_settings WHERE key IN (`+strings.Join(placeholders, ",")+`)`,
		args...,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	for rows.Next() {
		var (
			setting    domain.AppSetting
			updatedRaw string
		)
		if err := rows.Scan(&setting.Key, &setting.Value, &updatedRaw); err != nil {
			return nil, err
		}
		setting.UpdatedAt = parseTimeOrNow(updatedRaw)
		out[setting.Key] = setting
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return out, nil
}

func (s *Store) SetAppSettings(values map[string]string, updatedAt time.Time) error {
	if len(values) == 0 {
		return nil
	}

	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			_ = tx.Rollback()
		}
	}()

	updatedValue := updatedAt.UTC().Format(time.RFC3339Nano)
	for key, value := range values {
		if _, err = s.execTx(
			tx,
			`INSERT INTO app_settings(key, value, updated_at) VALUES(?, ?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at`,
			key,
			value,
			updatedValue,
		); err != nil {
			return err
		}
	}

	return tx.Commit()
}

func (s *Store) GetLatestScanStatus() (domain.ScanStatus, error) {
	status := domain.ScanStatus{}
	row := s.queryRow(
		`SELECT started_at, finished_at, video_count, error
FROM scan_runs ORDER BY id DESC LIMIT 1`,
	)

	var (
		startedRaw  string
		finishedRaw string
		videoCount  int
		scanErr     string
	)
	err := row.Scan(&startedRaw, &finishedRaw, &videoCount, &scanErr)
	if errors.Is(err, sql.ErrNoRows) {
		count, countErr := s.countVideos()
		if countErr != nil {
			return status, countErr
		}
		status.VideoCount = count
		return status, nil
	}
	if err != nil {
		return status, err
	}

	started := parseTimeOrNow(startedRaw)
	finished := parseTimeOrNow(finishedRaw)
	status.LastStartedAt = &started
	status.LastFinishedAt = &finished
	status.VideoCount = videoCount
	status.Error = scanErr
	return status, nil
}

func (s *Store) ListVideoDirectories(mediaType string) ([]string, error) {
	query := `SELECT DISTINCT directory FROM videos`
	var args []any
	if t := normalizeMediaType(mediaType); t != "" {
		query += ` WHERE media_type = ?`
		args = append(args, t)
	}

	rows, err := s.query(query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := make([]string, 0, 32)
	for rows.Next() {
		var dir string
		if err := rows.Scan(&dir); err != nil {
			return nil, err
		}
		out = append(out, dir)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return out, nil
}

func (s *Store) countVideos() (int, error) {
	row := s.queryRow(`SELECT COUNT(1) FROM videos`)
	var count int
	if err := row.Scan(&count); err != nil {
		return 0, err
	}
	return count, nil
}

func (s *Store) countByQuery(query string, args []any) (int, error) {
	row := s.queryRow(query, args...)
	var count int
	if err := row.Scan(&count); err != nil {
		return 0, err
	}
	return count, nil
}

func (s *Store) listSubtitlesByVideoID(videoID string) ([]domain.Subtitle, error) {
	rows, err := s.query(
		`SELECT id, path, file_name, language, format, size, mod_time, source, source_detail
FROM subtitles WHERE video_id = ? ORDER BY file_name ASC`,
		videoID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := make([]domain.Subtitle, 0, 8)
	for rows.Next() {
		var (
			sub      domain.Subtitle
			modValue string
		)
		if err := rows.Scan(
			&sub.ID,
			&sub.Path,
			&sub.FileName,
			&sub.Language,
			&sub.Format,
			&sub.Size,
			&modValue,
			&sub.Source,
			&sub.SourceDetail,
		); err != nil {
			return nil, err
		}
		sub.ModTime = parseTimeOrNow(modValue)
		sub = normalizeSubtitleSource(sub)
		out = append(out, sub)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return out, nil
}

func (s *Store) attachSubtitles(videos []domain.Video) error {
	if len(videos) == 0 {
		return nil
	}

	placeholders := make([]string, len(videos))
	args := make([]any, len(videos))
	indexByID := make(map[string]int, len(videos))
	for i, v := range videos {
		placeholders[i] = "?"
		args[i] = v.ID
		indexByID[v.ID] = i
		videos[i].Subtitles = []domain.Subtitle{}
	}

	query := `SELECT video_id, id, path, file_name, language, format, size, mod_time, source, source_detail
FROM subtitles WHERE video_id IN (` + strings.Join(placeholders, ",") + `) ORDER BY file_name ASC`

	rows, err := s.query(query, args...)
	if err != nil {
		return err
	}
	defer rows.Close()

	for rows.Next() {
		var (
			videoID  string
			sub      domain.Subtitle
			modValue string
		)
		if err := rows.Scan(
			&videoID,
			&sub.ID,
			&sub.Path,
			&sub.FileName,
			&sub.Language,
			&sub.Format,
			&sub.Size,
			&modValue,
			&sub.Source,
			&sub.SourceDetail,
		); err != nil {
			return err
		}
		sub.ModTime = parseTimeOrNow(modValue)
		sub = normalizeSubtitleSource(sub)
		idx, ok := indexByID[videoID]
		if !ok {
			continue
		}
		videos[idx].Subtitles = append(videos[idx].Subtitles, sub)
	}
	return rows.Err()
}

func (s *Store) loadSubtitleSourcesTx(tx *sql.Tx, videoID string) (map[string]subtitleSourceInfo, error) {
	query := `SELECT path, source, source_detail FROM subtitles`
	args := []any{}
	if strings.TrimSpace(videoID) != "" {
		query += ` WHERE video_id = ?`
		args = append(args, videoID)
	}

	rows, err := s.queryTx(tx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := make(map[string]subtitleSourceInfo, 32)
	for rows.Next() {
		var (
			pathValue string
			info      subtitleSourceInfo
		)
		if err := rows.Scan(&pathValue, &info.Source, &info.SourceDetail); err != nil {
			return nil, err
		}
		info.Source = normalizeSubtitleSourceValue(info.Source)
		info.SourceDetail = strings.TrimSpace(info.SourceDetail)
		out[subtitlePathKey(pathValue)] = info
	}
	return out, rows.Err()
}

func mergeSubtitleSource(sub domain.Subtitle, existing map[string]subtitleSourceInfo) domain.Subtitle {
	source := strings.TrimSpace(sub.Source)
	detail := strings.TrimSpace(sub.SourceDetail)
	if source == "" || (normalizeSubtitleSourceValue(source) == domain.SubtitleSourceDirectory && detail == "") {
		if info, ok := existing[subtitlePathKey(sub.Path)]; ok {
			sub.Source = info.Source
			sub.SourceDetail = info.SourceDetail
			return normalizeSubtitleSource(sub)
		}
	}
	return normalizeSubtitleSource(sub)
}

func normalizeSubtitleSource(sub domain.Subtitle) domain.Subtitle {
	sub.Source = normalizeSubtitleSourceValue(sub.Source)
	sub.SourceDetail = strings.TrimSpace(sub.SourceDetail)
	return sub
}

func normalizeSubtitleSourceValue(source string) string {
	switch strings.ToLower(strings.TrimSpace(source)) {
	case domain.SubtitleSourceUpload:
		return domain.SubtitleSourceUpload
	case domain.SubtitleSourceGenerated:
		return domain.SubtitleSourceGenerated
	default:
		return domain.SubtitleSourceDirectory
	}
}

func subtitlePathKey(pathValue string) string {
	normalized := filepath.Clean(strings.TrimSpace(pathValue))
	normalized = strings.ReplaceAll(normalized, "\\", "/")
	return strings.ToLower(normalized)
}

func (s *Store) backfillSubtitleSources() error {
	type backfillInfo struct {
		targetPath   string
		source       string
		sourceDetail string
	}

	rows, err := s.query(
		`SELECT target_path, action, message
FROM operation_logs
WHERE status = 'ok'
  AND action IN ('upload', 'replace', 'convert')
  AND trim(target_path) != ''
ORDER BY timestamp ASC`,
	)
	if err != nil {
		return err
	}
	defer rows.Close()

	latestByPath := make(map[string]backfillInfo, 32)
	for rows.Next() {
		var targetPath, action, message string
		if err := rows.Scan(&targetPath, &action, &message); err != nil {
			return err
		}
		info := backfillInfo{targetPath: targetPath}
		switch action {
		case "convert":
			info.source = domain.SubtitleSourceGenerated
			info.sourceDetail = strings.TrimSpace(strings.TrimPrefix(message, "generated from "))
		default:
			info.source = domain.SubtitleSourceUpload
			info.sourceDetail = filepath.Base(targetPath)
		}
		latestByPath[subtitlePathKey(targetPath)] = info
	}
	if err := rows.Err(); err != nil {
		return err
	}

	for _, info := range latestByPath {
		if info.sourceDetail == "" || info.sourceDetail == "." {
			info.sourceDetail = filepath.Base(info.targetPath)
		}
		if _, err := s.exec(
			`UPDATE subtitles SET source = ?, source_detail = ? WHERE lower(path) = lower(?)`,
			info.source,
			info.sourceDetail,
			info.targetPath,
		); err != nil {
			return err
		}
	}
	return nil
}

func (s *Store) migrateInitialSQLiteData(sqlitePath string) error {
	if s.dialect != dialectPostgres {
		return nil
	}

	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	committed := false
	defer func() {
		if !committed {
			_ = tx.Rollback()
		}
	}()

	if _, err = s.execTx(tx, `SELECT pg_advisory_xact_lock(?)`, int64(93070001)); err != nil {
		return fmt.Errorf("lock sqlite import migration: %w", err)
	}

	applied, err := s.isDataMigrationAppliedTx(tx, sqliteInitialDataMigration)
	if err != nil {
		return err
	}
	if applied {
		if err := tx.Commit(); err != nil {
			return err
		}
		committed = true
		return nil
	}

	targetRows, err := s.businessRowCountTx(tx)
	if err != nil {
		return err
	}
	if targetRows > 0 {
		return fmt.Errorf("postgres database already contains %d business rows; refusing to import sqlite data without migration marker", targetRows)
	}

	sourcePath := strings.TrimSpace(sqlitePath)
	if sourcePath == "" {
		if err := s.insertDataMigrationMarkerTx(tx, sqliteInitialDataMigration, "", "sqlite source not configured"); err != nil {
			return err
		}
		if err := tx.Commit(); err != nil {
			return err
		}
		committed = true
		return nil
	}

	absSourcePath, err := filepath.Abs(sourcePath)
	if err != nil {
		return err
	}
	stat, err := os.Stat(absSourcePath)
	if errors.Is(err, os.ErrNotExist) {
		if err := s.insertDataMigrationMarkerTx(tx, sqliteInitialDataMigration, absSourcePath, "sqlite source not found"); err != nil {
			return err
		}
		if err := tx.Commit(); err != nil {
			return err
		}
		committed = true
		return nil
	}
	if err != nil {
		return err
	}
	if stat.IsDir() {
		return fmt.Errorf("sqlite migration source is a directory: %s", absSourcePath)
	}
	backupPath, err := backupSQLiteSource(absSourcePath)
	if err != nil {
		return fmt.Errorf("backup sqlite migration source: %w", err)
	}

	source, err := openSQLite(absSourcePath)
	if err != nil {
		return fmt.Errorf("open sqlite migration source: %w", err)
	}
	defer func() {
		_ = source.Close()
	}()

	sourceRows, err := source.businessRowCount()
	if err != nil {
		return err
	}
	if sourceRows == 0 {
		if err := s.insertDataMigrationMarkerTx(tx, sqliteInitialDataMigration, absSourcePath, "sqlite source empty; backup="+backupPath); err != nil {
			return err
		}
		if err := tx.Commit(); err != nil {
			return err
		}
		committed = true
		return nil
	}

	if _, err := s.copyTableRowsTx(tx, source, "videos", []string{
		"id", "path", "directory", "file_name", "title", "original_title", "year", "imdb_id", "tmdb_id", "media_type", "metadata_source", "series_title", "series_original_title", "series_imdb_id", "series_tmdb_id", "poster_path", "updated_at",
	}, "id"); err != nil {
		return err
	}
	if _, err := s.copyTableRowsTx(tx, source, "subtitles", []string{
		"id", "video_id", "path", "file_name", "language", "format", "size", "mod_time", "updated_at", "source", "source_detail",
	}, "id"); err != nil {
		return err
	}
	if _, err := s.copyTableRowsTx(tx, source, "scan_runs", []string{
		"id", "started_at", "finished_at", "video_count", "error",
	}, "id"); err != nil {
		return err
	}
	if _, err := s.copyTableRowsTx(tx, source, "operation_logs", []string{
		"id", "timestamp", "action", "video_id", "target_path", "backup_path", "status", "message",
	}, "id"); err != nil {
		return err
	}
	if _, err := s.copyTableRowsTx(tx, source, "app_settings", []string{
		"key", "value", "updated_at",
	}, "key"); err != nil {
		return err
	}
	if _, err := s.execTx(tx, `SELECT setval(pg_get_serial_sequence('scan_runs', 'id'), COALESCE((SELECT MAX(id) FROM scan_runs), 1), (SELECT MAX(id) FROM scan_runs) IS NOT NULL)`); err != nil {
		return fmt.Errorf("reset scan_runs identity: %w", err)
	}

	if err := s.insertDataMigrationMarkerTx(tx, sqliteInitialDataMigration, absSourcePath, fmt.Sprintf("imported %d sqlite business rows; backup=%s", sourceRows, backupPath)); err != nil {
		return err
	}
	if err := tx.Commit(); err != nil {
		return err
	}
	committed = true
	return nil
}

func (s *Store) isDataMigrationAppliedTx(tx *sql.Tx, name string) (bool, error) {
	row := s.queryRowTx(tx, `SELECT COUNT(1) FROM data_migrations WHERE name = ?`, name)
	var count int
	if err := row.Scan(&count); err != nil {
		return false, err
	}
	return count > 0, nil
}

func (s *Store) insertDataMigrationMarkerTx(tx *sql.Tx, name string, source string, details string) error {
	_, err := s.execTx(
		tx,
		`INSERT INTO data_migrations(name, source, applied_at, details) VALUES(?, ?, ?, ?)`,
		name,
		source,
		time.Now().UTC().Format(time.RFC3339Nano),
		details,
	)
	return err
}

func (s *Store) businessRowCount() (int, error) {
	total := 0
	for _, tableName := range businessTables() {
		row := s.queryRow(`SELECT COUNT(1) FROM ` + tableName)
		var count int
		if err := row.Scan(&count); err != nil {
			return 0, err
		}
		total += count
	}
	return total, nil
}

func (s *Store) businessRowCountTx(tx *sql.Tx) (int, error) {
	total := 0
	for _, tableName := range businessTables() {
		row := s.queryRowTx(tx, `SELECT COUNT(1) FROM `+tableName)
		var count int
		if err := row.Scan(&count); err != nil {
			return 0, err
		}
		total += count
	}
	return total, nil
}

func businessTables() []string {
	return []string{"videos", "subtitles", "scan_runs", "operation_logs", "app_settings"}
}

func (s *Store) copyTableRowsTx(tx *sql.Tx, source *Store, tableName string, columns []string, orderBy string) (int, error) {
	selectQuery := `SELECT ` + strings.Join(columns, ", ") + ` FROM ` + tableName
	if strings.TrimSpace(orderBy) != "" {
		selectQuery += ` ORDER BY ` + orderBy
	}

	rows, err := source.query(selectQuery)
	if err != nil {
		return 0, fmt.Errorf("query sqlite %s: %w", tableName, err)
	}
	defer rows.Close()

	insertQuery := `INSERT INTO ` + tableName + `(` + strings.Join(columns, ", ") + `) VALUES(` + placeholders(len(columns)) + `)`
	values := make([]any, len(columns))
	scanTargets := make([]any, len(columns))
	for i := range scanTargets {
		scanTargets[i] = &values[i]
	}

	count := 0
	for rows.Next() {
		for i := range values {
			values[i] = nil
		}
		if err := rows.Scan(scanTargets...); err != nil {
			return count, fmt.Errorf("scan sqlite %s: %w", tableName, err)
		}
		for i, value := range values {
			if raw, ok := value.([]byte); ok {
				values[i] = string(raw)
			}
		}
		if _, err := s.execTx(tx, insertQuery, values...); err != nil {
			return count, fmt.Errorf("insert postgres %s: %w", tableName, err)
		}
		count += 1
	}
	if err := rows.Err(); err != nil {
		return count, err
	}
	return count, nil
}

func backupSQLiteSource(dbPath string) (string, error) {
	timestamp := time.Now().UTC().Format("20060102T150405.000000000Z")
	backupPath := dbPath + ".backup-" + timestamp
	copied := []string{}

	if err := copyFileExclusive(dbPath, backupPath); err != nil {
		return "", err
	}
	copied = append(copied, backupPath)

	for _, suffix := range []string{"-wal", "-shm"} {
		sourcePath := dbPath + suffix
		if _, err := os.Stat(sourcePath); errors.Is(err, os.ErrNotExist) {
			continue
		} else if err != nil {
			removeFiles(copied)
			return "", err
		}

		targetPath := backupPath + suffix
		if err := copyFileExclusive(sourcePath, targetPath); err != nil {
			removeFiles(copied)
			return "", err
		}
		copied = append(copied, targetPath)
	}

	return backupPath, nil
}

func copyFileExclusive(sourcePath string, targetPath string) error {
	info, err := os.Stat(sourcePath)
	if err != nil {
		return err
	}
	if info.IsDir() {
		return fmt.Errorf("source is a directory: %s", sourcePath)
	}

	source, err := os.Open(sourcePath)
	if err != nil {
		return err
	}
	defer source.Close()

	target, err := os.OpenFile(targetPath, os.O_WRONLY|os.O_CREATE|os.O_EXCL, info.Mode().Perm())
	if err != nil {
		return err
	}
	success := false
	defer func() {
		_ = target.Close()
		if !success {
			_ = os.Remove(targetPath)
		}
	}()

	if _, err := io.Copy(target, source); err != nil {
		return err
	}
	if err := target.Sync(); err != nil {
		return err
	}
	if err := target.Close(); err != nil {
		return err
	}
	success = true
	return nil
}

func removeFiles(paths []string) {
	for _, path := range paths {
		_ = os.Remove(path)
	}
}

func (s *Store) migrate() error {
	if _, err := s.exec(`
CREATE TABLE IF NOT EXISTS schema_migrations (
  version INTEGER PRIMARY KEY,
  applied_at TEXT NOT NULL
)`); err != nil {
		return err
	}

	applied, err := s.isMigrationApplied(1)
	if err != nil {
		return err
	}
	if !applied {
		tx, err := s.db.Begin()
		if err != nil {
			return err
		}
		defer func() {
			if err != nil {
				_ = tx.Rollback()
			}
		}()

		if err = s.execScriptTx(tx, s.migrationV1SQL()); err != nil {
			return fmt.Errorf("apply migration v1: %w", err)
		}
		if _, err = s.execTx(tx, `INSERT INTO schema_migrations(version, applied_at) VALUES(?, ?)`, 1, time.Now().UTC().Format(time.RFC3339Nano)); err != nil {
			return err
		}
		if err = tx.Commit(); err != nil {
			return err
		}
	}

	applied, err = s.isMigrationApplied(2)
	if err != nil {
		return err
	}
	if !applied {
		hasMediaType, err := s.hasColumn("videos", "media_type")
		if err != nil {
			return err
		}
		if !hasMediaType {
			if err := s.execScript(migrationV2); err != nil {
				return fmt.Errorf("apply migration v2: %w", err)
			}
		}
		if _, err = s.exec(`INSERT INTO schema_migrations(version, applied_at) VALUES(?, ?)`, 2, time.Now().UTC().Format(time.RFC3339Nano)); err != nil {
			return err
		}
	}

	applied, err = s.isMigrationApplied(3)
	if err != nil {
		return err
	}
	if !applied {
		hasPosterPath, err := s.hasColumn("videos", "poster_path")
		if err != nil {
			return err
		}
		if !hasPosterPath {
			if _, err := s.exec(migrationV3); err != nil {
				return fmt.Errorf("apply migration v3: %w", err)
			}
		}
		if _, err := s.exec(`INSERT INTO schema_migrations(version, applied_at) VALUES(?, ?)`, 3, time.Now().UTC().Format(time.RFC3339Nano)); err != nil {
			return err
		}
	}

	applied, err = s.isMigrationApplied(4)
	if err != nil {
		return err
	}
	if !applied {
		if err := s.execScript(migrationV4); err != nil {
			return fmt.Errorf("apply migration v4: %w", err)
		}
		if _, err := s.exec(`INSERT INTO schema_migrations(version, applied_at) VALUES(?, ?)`, 4, time.Now().UTC().Format(time.RFC3339Nano)); err != nil {
			return err
		}
	}

	applied, err = s.isMigrationApplied(5)
	if err != nil {
		return err
	}
	if !applied {
		hasSource, err := s.hasColumn("subtitles", "source")
		if err != nil {
			return err
		}
		if !hasSource {
			if _, err := s.exec(migrationV5AddSource); err != nil {
				return fmt.Errorf("apply migration v5 source: %w", err)
			}
		}
		hasSourceDetail, err := s.hasColumn("subtitles", "source_detail")
		if err != nil {
			return err
		}
		if !hasSourceDetail {
			if _, err := s.exec(migrationV5AddSourceDetail); err != nil {
				return fmt.Errorf("apply migration v5 source_detail: %w", err)
			}
		}
		if err := s.backfillSubtitleSources(); err != nil {
			return fmt.Errorf("backfill migration v5 subtitle sources: %w", err)
		}
		if _, err := s.exec(`INSERT INTO schema_migrations(version, applied_at) VALUES(?, ?)`, 5, time.Now().UTC().Format(time.RFC3339Nano)); err != nil {
			return err
		}
	}

	applied, err = s.isMigrationApplied(6)
	if err != nil {
		return err
	}
	if !applied {
		for _, column := range migrationV6VideoMetadataColumns {
			hasMetadataColumn, err := s.hasColumn("videos", column.name)
			if err != nil {
				return err
			}
			if !hasMetadataColumn {
				if _, err := s.exec(column.statement); err != nil {
					return fmt.Errorf("apply migration v6 %s: %w", column.name, err)
				}
			}
		}
		if _, err := s.exec(`INSERT INTO schema_migrations(version, applied_at) VALUES(?, ?)`, 6, time.Now().UTC().Format(time.RFC3339Nano)); err != nil {
			return err
		}
	}

	if s.dialect == dialectPostgres {
		if _, err := s.exec(`
CREATE TABLE IF NOT EXISTS data_migrations (
  name TEXT PRIMARY KEY,
  source TEXT NOT NULL DEFAULT '',
  applied_at TEXT NOT NULL,
  details TEXT NOT NULL DEFAULT ''
)`); err != nil {
			return fmt.Errorf("create data migrations table: %w", err)
		}
	}

	return nil
}

func (s *Store) isMigrationApplied(version int) (bool, error) {
	row := s.queryRow(`SELECT COUNT(1) FROM schema_migrations WHERE version = ?`, version)
	var count int
	if err := row.Scan(&count); err != nil {
		return false, err
	}
	return count > 0, nil
}

func (s *Store) hasColumn(tableName string, columnName string) (bool, error) {
	if s.dialect == dialectPostgres {
		row := s.queryRow(
			`SELECT COUNT(1)
FROM information_schema.columns
WHERE table_schema = current_schema()
  AND table_name = ?
  AND column_name = ?`,
			tableName,
			columnName,
		)
		var count int
		if err := row.Scan(&count); err != nil {
			return false, err
		}
		return count > 0, nil
	}

	rows, err := s.query(`PRAGMA table_info(` + tableName + `)`)
	if err != nil {
		return false, err
	}
	defer rows.Close()

	for rows.Next() {
		var (
			cid        int
			name       string
			colType    string
			notNull    int
			defaultV   any
			primaryKey int
		)
		if err := rows.Scan(&cid, &name, &colType, &notNull, &defaultV, &primaryKey); err != nil {
			return false, err
		}
		if strings.EqualFold(name, columnName) {
			return true, nil
		}
	}
	return false, rows.Err()
}

func normalizeMediaType(mediaType string) string {
	switch strings.ToLower(strings.TrimSpace(mediaType)) {
	case domain.MediaTypeMovie:
		return domain.MediaTypeMovie
	case domain.MediaTypeTV:
		return domain.MediaTypeTV
	default:
		return ""
	}
}

func normalizeSortBy(sortBy string) string {
	switch strings.ToLower(strings.TrimSpace(sortBy)) {
	case "year":
		return "year"
	default:
		return ""
	}
}

func normalizeSortOrder(sortOrder string) string {
	switch strings.ToLower(strings.TrimSpace(sortOrder)) {
	case "asc":
		return "asc"
	default:
		return "desc"
	}
}

func (s *Store) buildVideoOrderBy(sortBy string, sortOrder string) string {
	if normalizeSortBy(sortBy) == "year" {
		emptyExpr := `CASE WHEN trim(ifnull(year, '')) = '' THEN 1 ELSE 0 END`
		yearExpr := `CAST(year AS INTEGER)`
		if s.dialect == dialectPostgres {
			emptyExpr = `CASE WHEN trim(coalesce(year, '')) = '' THEN 1 ELSE 0 END`
			yearExpr = `CASE WHEN trim(coalesce(year, '')) ~ '^[0-9]+$' THEN CAST(year AS INTEGER) ELSE 0 END`
		}
		if normalizeSortOrder(sortOrder) == "asc" {
			return `ORDER BY ` + emptyExpr + ` ASC, ` + yearExpr + ` ASC, title ASC, path ASC`
		}
		return `ORDER BY ` + emptyExpr + ` ASC, ` + yearExpr + ` DESC, title ASC, path ASC`
	}
	return `ORDER BY title ASC, path ASC`
}

func defaultMediaType(mediaType string) string {
	normalized := normalizeMediaType(mediaType)
	if normalized == "" {
		return domain.MediaTypeMovie
	}
	return normalized
}

func scanVideoRow(rows *sql.Rows) (domain.Video, error) {
	var (
		video      domain.Video
		posterPath string
		updatedRaw string
	)
	if err := rows.Scan(
		&video.ID,
		&video.Path,
		&video.Directory,
		&video.FileName,
		&video.Title,
		&video.OriginalTitle,
		&video.Year,
		&video.ImdbID,
		&video.TmdbID,
		&video.MediaType,
		&video.MetadataSource,
		&video.SeriesTitle,
		&video.SeriesOriginalTitle,
		&video.SeriesImdbID,
		&video.SeriesTmdbID,
		&posterPath,
		&updatedRaw,
	); err != nil {
		return domain.Video{}, err
	}
	video.PosterPath = posterPath
	video.UpdatedAt = parseTimeOrNow(updatedRaw)
	return video, nil
}

func parseTimeOrNow(raw string) time.Time {
	t, err := time.Parse(time.RFC3339Nano, raw)
	if err != nil {
		return time.Now().UTC()
	}
	return t
}
